namespace ScarletScreen.Model
{
    public static class LanguageHelper
    {
        public static string GetLanguageName(string languageCode)
        {
            switch (languageCode.ToLower())
            {
                        case "an":
							return "Aragonese";
						case "ak":
							return "Akan";
						case "cr":
							return "Cree";
						case "az":
							return "Azerbaijani";
						case "cs":
							return "Czech";
						case "aa":
							return "Afar";
						case "br":
							return "Breton";
						case "af":
							return "Afrikaans";
						case "bo":
							return "Tibetan";
						case "ce":
							return "Chechen";
						case "kw":
							return "Cornish";
						case "fo":
							return "Faroese";
						case "la":
							return "Latin";
						case "ng":
							return "Ndonga";
						case "sc":
							return "Sardinian";
						case "ti":
							return "Tigrinya";
						case "tn":
							return "Tswana";
						case "tr":
							return "Turkish";
						case "pa":
							return "Punjabi";
						case "et":
							return "Estonian";
						case "fr":
							return "French";
						case "ha":
							return "Hausa";
						case "is":
							return "Icelandic";
						case "li":
							return "Limburgish";
						case "ln":
							return "Lingala";
						case "ss":
							return "Swati";
						case "ab":
							return "Abkhazian";
						case "sh":
							return "Serbo-Croatian";
						case "eu":
							return "Basque";
						case "fy":
							return "Frisian";
						case "ja":
							return "Japanese";
						case "oj":
							return "Ojibwa";
						case "or":
							return "Oriya";
						case "pi":
							return "Pali";
						case "su":
							return "Sundanese";
						case "th":
							return "Thai";
						case "ig":
							return "Igbo";
						case "id":
							return "Indonesian";
						case "kk":
							return "Kazakh";
						case "ki":
							return "Kikuyu";
						case "ug":
							return "Uighur";
						case "ve":
							return "Venda";
						case "rw":
							return "Kinyarwanda";
						case "mi":
							return "Maori";
						case "nv":
							return "Navajo";
						case "hi":
							return "Hindi";
						case "pt":
							return "Portuguese";
						case "sg":
							return "Sango";
						case "sk":
							return "Slovak";
						case "sr":
							return "Serbian";
						case "ty":
							return "Tahitian";
						case "xh":
							return "Xhosa";
						case "ar":
							return "Arabic";
						case "co":
							return "Corsican";
						case "bi":
							return "Bislama";
						case "eo":
							return "Esperanto";
						case "hz":
							return "Herero";
						case "fi":
							return "Finnish";
						case "iu":
							return "Inuktitut";
						case "lv":
							return "Latvian";
						case "it":
							return "Italian";
						case "nl":
							return "Dutch";
						case "kn":
							return "Kannada";
						case "sa":
							return "Sanskrit";
						case "sq":
							return "Albanian";
						case "tl":
							return "Tagalog";
						case "lb":
							return "Letzeburgesch";
						case "ts":
							return "Tsonga";
						case "ml":
							return "Malayalam";
						case "vo":
							return "Volapük";
						case "zu":
							return "Zulu";
						case "os":
							return "Ossetian; Ossetic";
						case "sm":
							return "Samoan";
						case "za":
							return "Zhuang";
						case "bn":
							return "Bengali";
						case "cu":
							return "Slavic";
						case "ga":
							return "Irish";
						case "gv":
							return "Manx";
						case "hu":
							return "Hungarian";
						case "jv":
							return "Javanese";
						case "kr":
							return "Kanuri";
						case "km":
							return "Khmer";
						case "ky":
							return "Kirghiz";
						case "na":
							return "Nauru";
						case "nr":
							return "Ndebele";
						case "oc":
							return "Occitan";
						case "ro":
							return "Romanian";
						case "ru":
							return "Russian";
						case "hy":
							return "Armenian";
						case "ch":
							return "Chamorro";
						case "xx":
							return "No Language";
						case "ba":
							return "Bashkir";
						case "gl":
							return "Galician";
						case "io":
							return "Ido";
						case "lu":
							return "Luba-Katanga";
						case "mh":
							return "Marshall";
						case "mg":
							return "Malagasy";
						case "mo":
							return "Moldavian";
						case "mn":
							return "Mongolian";
						case "nd":
							return "Ndebele";
						case "no":
							return "Norwegian";
						case "pl":
							return "Polish";
						case "sw":
							return "Swahili";
						case "tg":
							return "Tajik";
						case "to":
							return "Tonga";
						case "wa":
							return "Walloon";
						case "yi":
							return "Yiddish";
						case "en":
							return "English";
						case "as":
							return "Assamese";
						case "gd":
							return "Gaelic";
						case "kl":
							return "Kalaallisut";
						case "my":
							return "Burmese";
						case "qu":
							return "Quechua";
						case "sn":
							return "Shona";
						case "uk":
							return "Ukrainian";
						case "fa":
							return "Persian";
						case "ka":
							return "Georgian";
						case "gu":
							return "Gujarati";
						case "av":
							return "Avaric";
						case "ae":
							return "Avestan";
						case "gn":
							return "Guarani";
						case "mt":
							return "Maltese";
						case "ne":
							return "Nepali";
						case "sv":
							return "Swedish";
						case "tt":
							return "Tatar";
						case "wo":
							return "Wolof";
						case "cn":
							return "Cantonese";
						case "cv":
							return "Chuvash";
						case "da":
							return "Danish";
						case "dz":
							return "Dzongkha";
						case "ny":
							return "Chichewa; Nyanja";
						case "rn":
							return "Rundi";
						case "st":
							return "Sotho";
						case "tk":
							return "Turkmen";
						case "uz":
							return "Uzbek";
						case "vi":
							return "Vietnamese";
						case "el":
							return "Greek";
						case "ca":
							return "Catalan";
						case "cy":
							return "Welsh";
						case "de":
							return "German";
						case "ks":
							return "Kashmiri";
						case "ms":
							return "Malay";
						case "nb":
							return "Norwegian Bokmål";
						case "rm":
							return "Raeto-Romance";
						case "si":
							return "Sinhalese";
						case "es":
							return "Spanish";
						case "te":
							return "Telugu";
						case "tw":
							return "Twi";
						case "ps":
							return "Pushto";
						case "bg":
							return "Bulgarian";
						case "mk":
							return "Macedonian";
						case "ik":
							return "Inupiaq";
						case "ko":
							return "Korean";
						case "lt":
							return "Lithuanian";
						case "om":
							return "Oromo";
						case "se":
							return "Northern Sami";
						case "so":
							return "Somali";
						case "ta":
							return "Tamil";
						case "ur":
							return "Urdu";
						case "am":
							return "Amharic";
						case "bs":
							return "Bosnian";
						case "dv":
							return "Divehi";
						case "ay":
							return "Aymara";
						case "bm":
							return "Bambara";
						case "ii":
							return "Yi";
						case "ie":
							return "Interlingue";
						case "kv":
							return "Komi";
						case "ku":
							return "Kurdish";
						case "nn":
							return "Norwegian Nynorsk";
						case "hr":
							return "Croatian";
						case "lo":
							return "Lao";
						case "zh":
							return "Chinese";

                default:
                    return "Unknown Language";
            }
        }
    }
}